feat: initialize the front end of proposition and question bank system
open-ct/OpenItem-old pull request #1
Opened 2021-07-31 09:27 UTC by stacker-l

Initialize the front-end framework of question bank and proposition system, use react as the project
framework, add antd, Axios, customize CRA, less, prop types, react app rewired, react Redux, react
router Dom and Redux dependencies, and add some project configuration files.

BREAKING CHANGE: empty

2021-08-07 07:03 UTC, bnuluohf commented
@stacker-l demo link?

2021-08-07 11:20 UTC, bnuluohf requested changes

2021-08-07 11:20 UTC, bnuluohf commented on package.json
> +{
最外层的packger.json没啥用

2021-08-07 11:20 UTC, bnuluohf commented on web-client/README.md
> +# Getting Started with Create React App
web-client改成web

2021-08-14 06:54 UTC, stacker-l commented on package.json
> +{
> @stacker-l演示链接？

https://www.chinamfgzs.cn/open-ct

2021-08-14 06:55 UTC, stacker-l commented on web-client/README.md
> +# Getting Started with Create React App
已修改

2021-08-28 07:13 UTC, bnuluohf commented on package.json
> +{
@stacker-l 你自己写的登录？这个不行哈，改一下

2022-07-21 13:51 UTC, merged